secret:
  facebook:
    clientId:     # [enter Client ID registered for your app here]
    clientSecret: # [enter Client ID registered for your app here]

  github:
    clientId:     # [enter Client ID registered for your app here]
    clientSecret: # [enter Client ID registered for your app here]

  google:
    clientId:     # [enter Client ID registered for your app here]
    clientSecret: # [enter Client ID registered for your app here]
